import { execSync } from 'node:child_process';
import * as fs from 'node:fs';
import { loadConfig as loadReleaseKitConfig } from '@releasekit/config';
import type { VersionOutput } from '@releasekit/core';
import { error, info, success, warn } from '@releasekit/core';
import { formatDuration, parseDuration } from './duration.js';
import { createOctokit } from './preview-github.js';
import { postStandingPRStatusSafe } from './standing-pr-status.js';
import { runNotesStep, runPublishStep, runVersionStep } from './steps.js';
import type { ReleaseOptions, ReleaseOutput } from './types.js';

const MANIFEST_MARKER = '<!-- releasekit-manifest -->';
const MANIFEST_SCHEMA_VERSION = 2;
const MANIFEST_SCHEMA_MIN_VERSION = 1;

export interface StandingPROptions {
  config?: string;
  projectDir: string;
  verbose: boolean;
  quiet: boolean;
  json: boolean;
  npmAuth?: string;
}

export interface StandingPRResult {
  action: 'created' | 'updated' | 'closed' | 'noop';
  prNumber?: number;
  prUrl?: string;
  versionOutput?: VersionOutput;
}

export interface StandingPRManifest {
  schemaVersion: 1 | 2;
  versionOutput: VersionOutput;
  releaseNotes: Record<string, string>;
  notesFiles: string[];
  createdAt: string;
  baseSha: string;
  /** ISO timestamp of when this standing PR was first created. Preserved across updates. Added in schema v2. */
  firstUpdatedAt?: string;
}

function getGitHubContext(): { owner: string; repo: string; token: string } | null {
  const repo = process.env.GITHUB_REPOSITORY;
  const token = process.env.GITHUB_TOKEN;

  if (!repo || !token) return null;

  const [owner, repoName] = repo.split('/');
  if (!owner || !repoName) return null;

  return { owner, repo: repoName, token };
}

function shouldSkipFromCommit(headSubject: string, skipPatterns: string[]): boolean {
  return skipPatterns.some((p) => headSubject.startsWith(p) || headSubject.includes(p));
}

function getHeadCommitSubject(cwd: string): string | null {
  try {
    return execSync('git log -1 --pretty=%s', { encoding: 'utf-8', cwd }).trim();
  } catch {
    return null;
  }
}

function getHeadSha(cwd: string): string {
  try {
    return execSync('git rev-parse HEAD', { encoding: 'utf-8', cwd }).trim();
  } catch (err) {
    throw new Error(`Failed to get HEAD SHA: ${err instanceof Error ? err.message : String(err)}`);
  }
}

function resetReleaseBranch(branch: string, base: string, cwd: string): void {
  execSync('git fetch origin', { encoding: 'utf-8', cwd, stdio: 'pipe' });

  // Check if branch exists on remote
  let remoteExists = false;
  try {
    execSync(`git ls-remote --exit-code --heads origin "${branch}"`, { encoding: 'utf-8', cwd, stdio: 'pipe' });
    remoteExists = true;
  } catch {
    remoteExists = false;
  }

  if (remoteExists) {
    // Reset existing branch to base
    try {
      execSync(`git checkout "${branch}"`, { encoding: 'utf-8', cwd, stdio: 'pipe' });
    } catch {
      execSync(`git checkout -b "${branch}"`, { encoding: 'utf-8', cwd, stdio: 'pipe' });
    }
    execSync(`git reset --hard "origin/${base}"`, { encoding: 'utf-8', cwd, stdio: 'pipe' });
  } else {
    // Create branch from base
    try {
      execSync(`git checkout -b "${branch}" "origin/${base}"`, { encoding: 'utf-8', cwd, stdio: 'pipe' });
    } catch {
      execSync(`git checkout "${branch}"`, { encoding: 'utf-8', cwd, stdio: 'pipe' });
      execSync(`git reset --hard "origin/${base}"`, { encoding: 'utf-8', cwd, stdio: 'pipe' });
    }
  }
}

function commitAndForcePush(branch: string, cwd: string): void {
  execSync('git add -A', { encoding: 'utf-8', cwd, stdio: 'pipe' });

  // Check if there's anything to commit
  const status = execSync('git status --porcelain', { encoding: 'utf-8', cwd }).trim();
  if (status) {
    execSync('git commit -m "chore: release preparation [skip ci]"', { encoding: 'utf-8', cwd, stdio: 'pipe' });
  }

  execSync(`git push --force-with-lease origin "${branch}"`, { encoding: 'utf-8', cwd, stdio: 'pipe' });
}

function renderPrBody(versionOutput: VersionOutput, releaseNotes: Record<string, string>): string {
  const lines: string[] = [
    '## Release',
    '',
    'This PR was automatically generated by [ReleaseKit](https://github.com/goosewobbler/releasekit).',
    'Merging this PR will publish the following packages:',
    '',
    '| Package | Version |',
    '|---------|---------|',
  ];

  for (const update of versionOutput.updates) {
    lines.push(`| \`${update.packageName}\` | ${update.newVersion} |`);
  }

  const hasNotes = Object.keys(releaseNotes).length > 0;
  if (hasNotes) {
    lines.push('', '### Release Notes', '');
    for (const [pkg, notes] of Object.entries(releaseNotes)) {
      const update = versionOutput.updates.find((u) => u.packageName === pkg);
      if (update) {
        lines.push(`#### ${pkg} — ${update.newVersion}`, '');
      } else {
        lines.push(`#### ${pkg}`, '');
      }
      lines.push(notes.trim(), '');
    }
  }

  lines.push('---', '> Merge this PR to publish. The release will be triggered automatically.');
  return lines.join('\n');
}

export function serializeManifest(m: StandingPRManifest): string {
  const json = JSON.stringify(m);
  const encoded = Buffer.from(json).toString('base64');
  return [
    MANIFEST_MARKER,
    '<details><summary>Release manifest (do not edit)</summary>',
    '',
    `<!-- base64 ${encoded} -->`,
    '',
    '</details>',
  ].join('\n');
}

export function parseManifest(commentBody: string): StandingPRManifest {
  const b64Match = commentBody.match(/<!-- base64 ([A-Za-z0-9+/=]+) -->/);
  if (!b64Match?.[1]) {
    throw new Error('Release manifest not found or malformed in PR comment');
  }

  let json: string;
  try {
    json = Buffer.from(b64Match[1], 'base64').toString('utf-8');
  } catch {
    throw new Error('Release manifest encoding is invalid');
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(json);
  } catch {
    throw new Error('Release manifest JSON is malformed');
  }

  const m = parsed as StandingPRManifest;
  if (m.schemaVersion < MANIFEST_SCHEMA_MIN_VERSION || m.schemaVersion > MANIFEST_SCHEMA_VERSION) {
    throw new Error(
      `Release manifest schema version ${m.schemaVersion} is incompatible (expected ${MANIFEST_SCHEMA_MIN_VERSION}–${MANIFEST_SCHEMA_VERSION}). Re-run 'standing-pr update' to regenerate.`,
    );
  }

  return m;
}

type OctokitInstance = ReturnType<typeof createOctokit>;

async function findManifestComment(
  octokit: OctokitInstance,
  owner: string,
  repo: string,
  prNumber: number,
): Promise<{ id: number; body: string } | null> {
  const iterator = octokit.paginate.iterator(octokit.rest.issues.listComments, {
    owner,
    repo,
    issue_number: prNumber,
    per_page: 100,
  });

  for await (const response of iterator) {
    for (const comment of response.data) {
      if (comment.body?.startsWith(MANIFEST_MARKER)) {
        return { id: comment.id, body: comment.body };
      }
    }
  }

  return null;
}

export async function findStandingPR(
  octokit: OctokitInstance,
  owner: string,
  repo: string,
  branch: string,
): Promise<{ number: number; url: string } | null> {
  const { data: prs } = await octokit.rest.pulls.list({
    owner,
    repo,
    head: `${owner}:${branch}`,
    state: 'open',
    per_page: 1,
  });

  const pr = prs[0];
  return pr ? { number: pr.number, url: pr.html_url } : null;
}

function buildBaseReleaseOptions(options: StandingPROptions, dryRun: boolean): ReleaseOptions {
  return {
    config: options.config,
    dryRun,
    sync: false,
    skipNotes: true,
    skipPublish: true,
    skipGit: true,
    skipGithubRelease: true,
    skipVerification: true,
    json: options.json,
    verbose: options.verbose,
    quiet: options.quiet,
    projectDir: options.projectDir,
    npmAuth: (options.npmAuth as ReleaseOptions['npmAuth']) ?? 'auto',
  };
}

export async function runStandingPRUpdate(options: StandingPROptions): Promise<StandingPRResult> {
  const cwd = options.projectDir;

  const releaseKitConfig = loadReleaseKitConfig({ cwd, configPath: options.config });
  const ciConfig = releaseKitConfig.ci;
  const standingPrConfig = ciConfig?.standingPr;

  const branch = standingPrConfig?.branch ?? 'release/next';
  const base = releaseKitConfig.git?.branch ?? 'main';
  const skipPatterns = releaseKitConfig.release?.ci?.skipPatterns ?? ['chore: release '];

  // Skip-pattern guard
  const headSubject = getHeadCommitSubject(cwd);
  if (headSubject && shouldSkipFromCommit(headSubject, skipPatterns)) {
    info(`Skipping standing PR update: commit matches skip pattern`);
    return { action: 'noop' };
  }

  // Dry-run version analysis to compute bumps without writing
  info('Running version analysis (dry run)...');
  const dryRunOptions = buildBaseReleaseOptions(options, true);
  const versionOutputDry = await runVersionStep(dryRunOptions);

  const githubContext = getGitHubContext();

  if (versionOutputDry.updates.length === 0) {
    info('No releasable changes found');

    if (githubContext) {
      const octokit = createOctokit(githubContext.token);
      const existing = await findStandingPR(octokit, githubContext.owner, githubContext.repo, branch);
      if (existing) {
        await octokit.rest.issues.createComment({
          owner: githubContext.owner,
          repo: githubContext.repo,
          issue_number: existing.number,
          body: 'No releasable changes found. Closing this PR as the release queue is empty.',
        });
        await octokit.rest.pulls.update({
          owner: githubContext.owner,
          repo: githubContext.repo,
          pull_number: existing.number,
          state: 'closed',
        });
        info(`Closed standing PR #${existing.number}`);
        return { action: 'closed', prNumber: existing.number, prUrl: existing.url };
      }
    }

    return { action: 'noop' };
  }

  // minPackages gate: close existing PR and noop if package count is below threshold
  const minPackages = standingPrConfig?.minPackages;
  if (minPackages !== undefined && versionOutputDry.updates.length < minPackages) {
    info(
      `Package count (${versionOutputDry.updates.length}) is below minPackages threshold (${minPackages}), skipping`,
    );
    if (githubContext) {
      const octokit = createOctokit(githubContext.token);
      const existing = await findStandingPR(octokit, githubContext.owner, githubContext.repo, branch);
      if (existing) {
        await octokit.rest.issues.createComment({
          owner: githubContext.owner,
          repo: githubContext.repo,
          issue_number: existing.number,
          body: `Not enough packages with releasable changes (${versionOutputDry.updates.length} of ${minPackages} required). Closing until the threshold is reached.`,
        });
        await octokit.rest.pulls.update({
          owner: githubContext.owner,
          repo: githubContext.repo,
          pull_number: existing.number,
          state: 'closed',
        });
        info(`Closed standing PR #${existing.number} (minPackages not met)`);
        return { action: 'closed', prNumber: existing.number, prUrl: existing.url };
      }
    }
    return { action: 'noop' };
  }

  // Capture baseSha before switching branches
  const baseSha = getHeadSha(cwd);

  // Branch management: reset release branch to base
  info(`Resetting release branch '${branch}' to origin/${base}...`);
  resetReleaseBranch(branch, base, cwd);

  // Materialize changes on release branch
  info('Writing version bumps...');
  const writeOptions = buildBaseReleaseOptions(options, false);
  const versionOutput = await runVersionStep(writeOptions);

  info('Generating release notes...');
  const notesOptions = { ...writeOptions, skipNotes: false };
  const notesResult = await runNotesStep(versionOutput, notesOptions);

  // Commit and force-push the release branch
  info(`Committing and pushing '${branch}'...`);
  commitAndForcePush(branch, cwd);

  // Capture the release branch HEAD SHA for the status check (we're still on the release branch)
  const releaseBranchSha = getHeadSha(cwd);

  success(`Release branch '${branch}' updated`);

  if (!githubContext) {
    warn('No GitHub context available — skipping PR creation');
    return { action: 'noop', versionOutput };
  }

  const octokit = createOctokit(githubContext.token);
  const { owner, repo } = githubContext;

  // Build PR title
  const count = versionOutput.updates.length;
  const firstUpdate = versionOutput.updates[0];
  /* biome-ignore lint/suspicious/noTemplateCurlyInString: template string uses config variable */
  const titleTemplate = standingPrConfig?.title ?? 'chore: release ${count} package(s)';
  const title = titleTemplate
    .replace(/\$\{count\}/g, String(count))
    .replace(/\$\{version\}/g, firstUpdate?.newVersion ?? '');

  const body = renderPrBody(versionOutput, notesResult.releaseNotes ?? {});
  const labels = standingPrConfig?.labels ?? ['release'];

  const existing = await findStandingPR(octokit, owner, repo, branch);

  let prNumber: number;
  let prUrl: string;
  let action: StandingPRResult['action'];

  if (existing) {
    await octokit.rest.pulls.update({
      owner,
      repo,
      pull_number: existing.number,
      title,
      body,
    });
    prNumber = existing.number;
    prUrl = existing.url;
    action = 'updated';
    info(`Updated standing PR #${prNumber}`);
  } else {
    const { data: newPr } = await octokit.rest.pulls.create({
      owner,
      repo,
      title,
      body,
      head: branch,
      base,
    });
    prNumber = newPr.number;
    prUrl = newPr.html_url;
    action = 'created';
    info(`Created standing PR #${prNumber}`);
  }

  // Apply labels
  if (labels.length > 0) {
    try {
      await octokit.rest.issues.setLabels({
        owner,
        repo,
        issue_number: prNumber,
        labels,
      });
    } catch {
      warn('Failed to apply labels to standing PR (labels may not exist in the repository)');
    }
  }

  // Find existing manifest to preserve firstUpdatedAt across updates
  let firstUpdatedAt = new Date().toISOString();
  const existingManifestComment = await findManifestComment(octokit, owner, repo, prNumber);
  if (existingManifestComment) {
    try {
      const existingManifest = parseManifest(existingManifestComment.body);
      if (existingManifest.firstUpdatedAt) {
        firstUpdatedAt = existingManifest.firstUpdatedAt;
      } else {
        firstUpdatedAt = existingManifest.createdAt;
      }
    } catch {
      // Use current time if the existing manifest can't be parsed
    }
  }

  // Store manifest as a bot comment
  const manifest: StandingPRManifest = {
    schemaVersion: 2,
    versionOutput,
    releaseNotes: notesResult.releaseNotes ?? {},
    notesFiles: notesResult.files,
    createdAt: new Date().toISOString(),
    baseSha,
    firstUpdatedAt,
  };

  const manifestBody = serializeManifest(manifest);
  if (existingManifestComment) {
    await octokit.rest.issues.updateComment({
      owner,
      repo,
      comment_id: existingManifestComment.id,
      body: manifestBody,
    });
  } else {
    await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body: manifestBody,
    });
  }
  success(`Manifest written to PR #${prNumber}`);

  // Post commit status check — gates determine pending vs success
  const minAge = standingPrConfig?.minAge;
  let statusState: 'success' | 'pending' = 'success';
  let statusDescription = 'Ready to merge';

  if (minAge !== undefined) {
    const minAgeMs = parseDuration(minAge);
    if (minAgeMs === null) {
      warn(
        `ci.standingPr.minAge value "${minAge}" is not a valid duration (e.g. "6h", "30m", "1d") — gate is inactive`,
      );
    } else if (manifest.firstUpdatedAt) {
      const ageMs = Date.now() - new Date(manifest.firstUpdatedAt).getTime();
      if (ageMs < minAgeMs) {
        statusState = 'pending';
        statusDescription = `Waiting ${formatDuration(minAgeMs - ageMs)} for minAge`;
      }
    }
  }

  await postStandingPRStatusSafe(octokit, owner, repo, releaseBranchSha, statusState, statusDescription);

  return { action, prNumber, prUrl, versionOutput };
}

export async function runStandingPRPublish(options: StandingPROptions): Promise<ReleaseOutput | null> {
  const cwd = options.projectDir;

  // Guard: verify this is triggered by the release PR being merged
  const eventPath = process.env.GITHUB_EVENT_PATH;
  if (!eventPath) {
    error('GITHUB_EVENT_PATH not set — standing-pr publish must run in GitHub Actions');
    return null;
  }

  let event: { pull_request?: { head?: { ref?: string }; number?: number; merged?: boolean } };
  try {
    event = JSON.parse(fs.readFileSync(eventPath, 'utf-8'));
  } catch (err) {
    error(`Failed to read GitHub event: ${err instanceof Error ? err.message : String(err)}`);
    return null;
  }

  const releaseKitConfig = loadReleaseKitConfig({ cwd, configPath: options.config });
  const standingPrConfig = releaseKitConfig.ci?.standingPr;
  const releaseBranch = standingPrConfig?.branch ?? 'release/next';

  const headRef = event.pull_request?.head?.ref;
  const merged = event.pull_request?.merged;
  const prNumber = event.pull_request?.number;

  if (!headRef || headRef !== releaseBranch) {
    info(`Skipping: merged PR head ref '${headRef}' does not match release branch '${releaseBranch}'`);
    return null;
  }

  if (!merged) {
    info('Skipping: PR was not merged');
    return null;
  }

  if (!prNumber) {
    error('Could not determine PR number from GitHub event');
    return null;
  }

  const githubContext = getGitHubContext();
  if (!githubContext) {
    error('No GitHub context (GITHUB_REPOSITORY or GITHUB_TOKEN) available');
    return null;
  }

  const octokit = createOctokit(githubContext.token);
  const { owner, repo } = githubContext;

  // Find and parse manifest from the merged PR
  const manifestComment = await findManifestComment(octokit, owner, repo, prNumber);
  if (!manifestComment) {
    throw new Error(`Release manifest not found on PR #${prNumber}. Re-run 'standing-pr update' to regenerate.`);
  }

  let manifest: StandingPRManifest;
  try {
    manifest = parseManifest(manifestComment.body);
  } catch (err) {
    throw new Error(
      `Release manifest on PR #${prNumber} is invalid or incompatible. Re-run 'standing-pr update'. Details: ${err instanceof Error ? err.message : String(err)}`,
    );
  }

  // Warn if manifest base is no longer an ancestor of current HEAD (history may be rewritten)
  const currentSha = getHeadSha(cwd);
  try {
    execSync(`git merge-base --is-ancestor "${manifest.baseSha}" "${currentSha}"`, {
      cwd,
      stdio: 'pipe',
    });
  } catch {
    warn(
      `Manifest baseSha (${manifest.baseSha}) is not an ancestor of current HEAD (${currentSha}) — history may have been rewritten`,
    );
  }

  info(`Publishing from manifest: ${manifest.versionOutput.updates.length} package(s)`);

  const publishOptions: ReleaseOptions = {
    config: options.config,
    dryRun: false,
    sync: false,
    skipNotes: true,
    skipPublish: false,
    skipGit: false,
    skipGitCommit: true,
    skipGithubRelease: false,
    skipVerification: false,
    json: options.json,
    verbose: options.verbose,
    quiet: options.quiet,
    projectDir: cwd,
    npmAuth: (options.npmAuth as ReleaseOptions['npmAuth']) ?? 'auto',
  };

  const publishOutput = await runPublishStep(
    manifest.versionOutput,
    publishOptions,
    manifest.releaseNotes,
    manifest.notesFiles,
  );

  success('Publish complete');

  // Cleanup: delete release branch if configured
  if (standingPrConfig?.deleteBranchOnMerge !== false) {
    try {
      execSync(`git push origin --delete "${releaseBranch}"`, { encoding: 'utf-8', cwd, stdio: 'pipe' });
      info(`Deleted release branch '${releaseBranch}'`);
    } catch (err) {
      const errorMsg = err instanceof Error ? err.message : String(err);
      if (errorMsg.includes('not found') || errorMsg.includes('does not exist')) {
        info(`Release branch '${releaseBranch}' already deleted`);
      } else {
        warn(`Failed to delete release branch '${releaseBranch}': ${errorMsg}`);
      }
    }
  }

  return {
    versionOutput: manifest.versionOutput,
    notesGenerated: false,
    releaseNotes: manifest.releaseNotes,
    publishOutput,
  };
}
