name: Unit Tests

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      cache_key:
        required: true
        type: string

env:
  TURBO_TELEMETRY_DISABLED: 1

jobs:
  unit-tests:
    name: Unit Tests [${{ inputs.os }}]
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2

      - name: Setup Development Environment
        uses: ./.github/workflows/actions/setup-workspace

      - name: Download build artifacts
        uses: ./.github/workflows/actions/download-archive
        with:
          name: releasekit-build
          cache_key: ${{ inputs.cache_key }}

      - name: Run unit tests with coverage
        run: pnpm test:coverage