name: Integration Tests

on:
  workflow_call:
    inputs:
      cache_key:
        required: true
        type: string

env:
  TURBO_TELEMETRY_DISABLED: 1

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Development Environment
        uses: ./.github/workflows/actions/setup-workspace

      - name: Download build artifacts
        uses: ./.github/workflows/actions/download-archive
        with:
          name: releasekit-build
          cache_key: ${{ inputs.cache_key }}

      - name: Run integration tests
        run: pnpm --filter @releasekit/integration-tests test
